accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, UserChangeView, UserPasswordChangeView, UserDetailView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='user_create'),
    path('<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('<int:pk>/change/', UserChangeView.as_view(), name='user_change'),
    path('<int:pk>/password_change/', UserPasswordChangeView.as_view(), name='password_change'),
]

controlwork_9/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# urls_api = [
#     path('v1/', include('api_v1.urls'))
# ]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    # path('api/', include(urls_api)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views import AdvertisementListView, AdvertisementModeratorListView, AdvertisementDetailView, \
    AdvertisementCreateView, AdvertisementUpdateView, MarkAsPendingDeletionView, CommentCreateView, CommentDeleteView, \
    ApproveAdvertisementView, RejectAdvertisementView

app_name = 'webapp'

urlpatterns = [
    path('', AdvertisementListView.as_view()),
    path('home/', AdvertisementListView.as_view(), name='index'),
    path('advertisement_list_moderator/', AdvertisementModeratorListView.as_view(), name='moderator_list'),
    path('advertisement/<int:pk>/', AdvertisementDetailView.as_view(), name='advertisement_detail'),
    path('advertisement/create/', AdvertisementCreateView.as_view(), name='create_advertisement'),
    path('advertisement/<int:pk>/update/', AdvertisementUpdateView.as_view(), name='update_advertisement'),
    path('advertisement/<int:pk>/mark_as_pending_deletion/', MarkAsPendingDeletionView.as_view(),
         name='mark_as_pending_deletion'),
    path('advertisement/<int:pk>/comment/create/', CommentCreateView.as_view(), name='comment_create'),
    path('comment/delete/<int:pk>/', CommentDeleteView.as_view(), name='comment_delete'),
    path('advertisement/<int:pk>/approve/', ApproveAdvertisementView.as_view(), name='approve_advertisement'),
    path('advertisement/<int:pk>/reject/', RejectAdvertisementView.as_view(), name='reject_advertisement'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    GENDER_CHOICES = [
        ('man', "Мужчина"),
        ('woman', "Женщина")
    ]
    avatar = models.ImageField(upload_to='users/avatars/', verbose_name='Аватар')
    user_information = models.TextField(null=True, blank=True, verbose_name='Информация о пользователе')
    phone_number = models.CharField(max_length=16, null=True, blank=True, verbose_name='номер телефона')
    gender = models.CharField(max_length=20, choices=GENDER_CHOICES, null=True, blank=True, verbose_name='пол')

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms


class MyUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = (
            'username', 'password1', 'password2', 'first_name', 'last_name', 'email', 'avatar', 'gender',
            'phone_number',
            'user_information')


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('phone_number',)

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        if not phone_number.startswith('+996') or not len(phone_number) == 16:
            raise forms.ValidationError(
                'Неправильный формат номера телефона. Пожалуйста, введите номер в формате: +996 XXX XXX XXX')
        return phone_number

accounts/views.py
from django.db.models import Q
from django.shortcuts import redirect, reverse
from django.contrib.auth import login, get_user_model
from django.views.generic import CreateView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.forms import MyUserCreationForm, UserChangeForm
from django.contrib.auth.views import PasswordChangeView

from webapp.models import Advertisement


class RegisterView(CreateView):
    model = get_user_model()
    form_class = MyUserCreationForm
    template_name = 'user_create.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_page = self.request.GET.get('next')
        if not next_page:
            next_page = self.request.POST.get('next')
        if not next_page:
            next_page = reverse('webapp:index')

        return next_page


class UserDetailView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        if self.request.user == user:
            context['advertisements'] = Advertisement.objects.filter(author=user).exclude(status='Pending deletion')
        else:
            context['advertisements'] = Advertisement.objects.filter(author=user, status='Published')
        return context


class UserChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    def get_queryset(self):
        return super().get_queryset().filter(id=self.request.user.id)

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.object.pk})


class UserPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'user_password_change.html'

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.request.user.pk})

accounts/templates/login.html
{% extends 'base.html' %}

{% block title %}Вход{% endblock %}
{% block menu %}<a class="nav-link" aria-current="page"  href="/">На главную</a>{% endblock %}

{% block content %}

    <h1 style="text-align: center">Вход</h1>

    <form action="" method="post" class="text-center">
        {% csrf_token %}
        {% if has_error %}
            <p class="form-error">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="mb-3 ">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input type="text" class="form-control mx-auto" id="username" name="username" style="max-width: 300px">
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Пароль:</label>
            <input type="password" class="form-control mx-auto" id="password" name="password"  style="max-width: 300px">
        </div>
        <button type="submit" class="btn btn-primary">Войти</button>
    </form>
{% endblock %}

accounts/templates/user_change.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}
{% block menu %}<a class="nav-link" aria-current="page" href="#">Назад</a>{% endblock %}

{% block content %}
    <h1>Поменять личные данные</h1>

        {% include 'partial/form.html' with form_method="post" is_data=True value_submit='Изменить'%}

{% endblock %}

accounts/templates/user_create.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}
{% block menu %}<a class="nav-link" aria-current="page"  href="#">На главную</a>{% endblock %}

{% block content %}
<h1>Регистрация</h1>
    {% include 'partial/form.html' with form_method="post" is_data=True value_submit='Зарегистрироваться'%}

{% endblock %}

accounts/templates/user_detail.html
{% extends 'base.html' %}

{% block title %}{{ user_obj.get_full_name }}{% endblock %}
{% block menu %}


{% endblock %}


{% if request.user.is_authenticated and request.user == user_obj %}
    <a class="nav-link" aria-current="page" href="">Редактировать</a>
    <a class="nav-link" aria-current="page" href="">Смена пароля</a>
{% endif %}
{% block content %}

    <div class="d-flex mt-5 mb-5">
        <div class="mx-5 align-self-center">
            <div class="d-inline-block rounded-circle overflow-hidden" style="width: 200px; height: 200px; ">
                <img src="{{ user_obj.avatar.url }}" class="object-fit-cover w-100 h-100" alt="...">
            </div>
        </div>
        <div class="mx-5 align-self-center">
            <div class="d-flex mb-3">
                <h2 class="fw-lighter">{{ user_obj.username }}</h2>
                {% if request.user.is_authenticated and request.user == user_obj %}
                    <a class="btn btn-outline-secondary align-self-center ms-3"
                       href="{% url 'accounts:user_change' request.user.pk %}"
                       role="button">Редактировать профиль</a>
                    <a class="btn btn-outline-secondary align-self-center ms-3"
                       href="{% url 'accounts:password_change' request.user.pk %}"
                       role="button">Смена пароля</a>
                {% endif %}
            </div>
            <p><b>Полное имя:</b> {{ user_obj.get_full_name }}</p>
            <p><b>Информация:</b> {{ user_obj.user_information }}</p>
            <p><b>Телефонный номер:</b> {{ user_obj.phone_number }}</p>
        </div>
    </div>

    <h3 class="mb-3">Все объявления:</h3>
    <div class="row">
        {% for ad in advertisements %}
            <div class="col-lg-4 col-md-6 mb-4">
                <a style="text-decoration: none" href="{% url 'webapp:advertisement_detail' ad.pk %}">
                    <div class="card" style="width: 300px; height: 480px">
                        <img style="width: 299px; height: 320px" src="{{ ad.photo.url }}" class="card-img-top"
                             alt="Photo">
                        <div class="card-body">
                            <span class="card-text"><b><a class="text-dark" style="text-decoration: none"
                                                       href="{% url 'accounts:user_detail' ad.author.pk %}">{{ ad.author }}</a></b>
                            </span><br>
                            <span>{{ ad.author.phone_number }}</span>
                            <p class="card-text"><b>Заголовок:</b> {{ ad.title }}</p>
                            <p class="card-text"><b>Цена:</b> {{ ad.price }} сом</p>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

accounts/templates/user_password_change.html
{% extends 'base.html' %}



{% block title %}Смена пароля{% endblock %}



{% block menu %}<a class="nav-link" aria-current="page" href="{% url 'accounts:user_detail' request.user.pk %}">Назад</a>{% endblock %}




{% block content %}

    <h1>Смена пароля</h1>

    {% include 'partial/form.html' with form_method="post" value_submit='Сохранить' %}

{% endblock %}