accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, UserChangeView, UserPasswordChangeView, UserDetailView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='user_create'),
    path('<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('<int:pk>/change/', UserChangeView.as_view(), name='user_change'),
    path('<int:pk>/password_change/', UserPasswordChangeView.as_view(), name='password_change'),
]

controlwork_9/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# urls_api = [
#     path('v1/', include('api_v1.urls'))
# ]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    # path('api/', include(urls_api)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views import AdvertisementListView, AdvertisementModeratorListView, AdvertisementDetailView, \
    AdvertisementCreateView, AdvertisementUpdateView, MarkAsPendingDeletionView, CommentCreateView, CommentDeleteView, \
    ApproveAdvertisementView, RejectAdvertisementView

app_name = 'webapp'

urlpatterns = [
    path('', AdvertisementListView.as_view()),
    path('home/', AdvertisementListView.as_view(), name='index'),
    path('advertisement_list_moderator/', AdvertisementModeratorListView.as_view(), name='moderator_list'),
    path('advertisement/<int:pk>/', AdvertisementDetailView.as_view(), name='advertisement_detail'),
    path('advertisement/create/', AdvertisementCreateView.as_view(), name='create_advertisement'),
    path('advertisement/<int:pk>/update/', AdvertisementUpdateView.as_view(), name='update_advertisement'),
    path('advertisement/<int:pk>/mark_as_pending_deletion/', MarkAsPendingDeletionView.as_view(),
         name='mark_as_pending_deletion'),
    path('advertisement/<int:pk>/comment/create/', CommentCreateView.as_view(), name='comment_create'),
    path('comment/delete/<int:pk>/', CommentDeleteView.as_view(), name='comment_delete'),
    path('advertisement/<int:pk>/approve/', ApproveAdvertisementView.as_view(), name='approve_advertisement'),
    path('advertisement/<int:pk>/reject/', RejectAdvertisementView.as_view(), name='reject_advertisement'),
]

webapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')

    def __str__(self):
        return self.name


class Advertisement(models.Model):
    STATUS_CHOICES = (
        ('Pending moderation', 'На модерацию'),
        ('Published', 'Опубликовано'),
        ('Rejected', 'Отклонено'),
        ('Pending deletion', 'На удаление'),
    )
    photo = models.ImageField(upload_to='advertisements/photos/', blank=True, null=True, verbose_name='Фото')
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE, verbose_name='Автор')
    category = models.ForeignKey('webapp.Category', on_delete=models.CASCADE, verbose_name='Категория')
    price = models.DecimalField(max_digits=10, decimal_places=0, verbose_name='Цена')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Pending moderation', verbose_name='Статус')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    published_at = models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')

    def __str__(self):
        return self.title


class Comment(models.Model):
    text = models.TextField(verbose_name='Комментарий')
    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE, verbose_name='Автор')
    advertisement = models.ForeignKey('webapp.Advertisement', on_delete=models.CASCADE, verbose_name='Объявление')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return f"Comment by {self.author.username} on {self.advertisement.title}"

webapp/forms.py
from django import forms
from .models import Advertisement


class AdvertisementForm(forms.ModelForm):
    class Meta:
        model = Advertisement
        fields = ['photo', 'title', 'description', 'category', 'price']

webapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from webapp.forms import AdvertisementForm
from webapp.models import Advertisement


class AdvertisementListView(ListView):
    model = Advertisement
    template_name = 'advertisement/index.html'
    context_object_name = 'published_ads'

    def get_queryset(self):
        return Advertisement.objects.filter(status='Published').order_by('-published_at')


class AdvertisementDetailView(DetailView):
    model = Advertisement
    template_name = 'advertisement/detail.html'
    context_object_name = 'advertisement'


class AdvertisementCreateView(CreateView):
    model = Advertisement
    template_name = 'advertisement/create_advertisement.html'
    form_class = AdvertisementForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('webapp:index')


class AdvertisementUpdateView(UpdateView):
    model = Advertisement
    template_name = 'advertisement/edit_advertisement.html'
    form_class = AdvertisementForm

    def get_success_url(self):
        return reverse_lazy('webapp:advertisement_detail', kwargs={'pk': self.object.pk})


class MarkAsPendingDeletionView(View):
    def post(self, request, *args, **kwargs):
        advertisement = Advertisement.objects.get(pk=kwargs['pk'])
        advertisement.status = 'Pending deletion'
        advertisement.save()
        return redirect('webapp:index')

webapp/views/advertisement_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from webapp.forms import AdvertisementForm
from webapp.models import Advertisement


class AdvertisementModeratorListView(ListView):
    model = Advertisement
    template_name = 'advertisement/advertisement_list_moderator.html'
    context_object_name = 'advertisements'


class AdvertisementListView(ListView):
    model = Advertisement
    template_name = 'advertisement/index.html'
    context_object_name = 'published_ads'

    def get_queryset(self):
        return Advertisement.objects.filter(status='Published').order_by('-published_at')


class AdvertisementDetailView(DetailView):
    model = Advertisement
    template_name = 'advertisement/detail.html'
    context_object_name = 'advertisement'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        advertisement = self.get_object()
        context['comments'] = advertisement.comment_set.order_by(
            '-created_at')
        return context


class AdvertisementCreateView(LoginRequiredMixin, CreateView):
    model = Advertisement
    template_name = 'advertisement/create_advertisement.html'
    form_class = AdvertisementForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('webapp:index')


class AdvertisementUpdateView(LoginRequiredMixin, UpdateView):
    model = Advertisement
    template_name = 'advertisement/edit_advertisement.html'
    form_class = AdvertisementForm

    def dispatch(self, request, *args, **kwargs):
        if self.get_object().author != self.request.user:
            return redirect('webapp:index')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('webapp:advertisement_detail', kwargs={'pk': self.object.pk})


class MarkAsPendingDeletionView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        advertisement = Advertisement.objects.get(pk=kwargs['pk'])
        if advertisement.author != request.user:
            return redirect('webapp:index')
        advertisement.status = 'Pending deletion'
        advertisement.save()
        return redirect('webapp:index')


class ApproveAdvertisementView(View):
    def post(self, request, *args, **kwargs):
        advertisement = Advertisement.objects.get(pk=kwargs['pk'])
        advertisement.status = 'Published'
        advertisement.save()
        return JsonResponse({'status': 'approved'})


class RejectAdvertisementView(View):
    def post(self, request, *args, **kwargs):
        advertisement = Advertisement.objects.get(pk=kwargs['pk'])
        advertisement.status = 'Rejected'
        advertisement.save()
        return JsonResponse({'status': 'rejected'})

webapp/views/comment_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.views import View
from webapp.models import Advertisement, Comment


class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk):
        text = request.POST.get('text')
        advertisement = get_object_or_404(Advertisement, pk=pk)
        user = request.user
        Comment.objects.create(text=text, advertisement=advertisement, author=user)
        return redirect('webapp:advertisement_detail', pk=pk)


class CommentDeleteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        comment = get_object_or_404(Comment, pk=pk)
        advertisement_pk = comment.advertisement.pk
        if request.user == comment.author:
            comment.delete()
            return redirect('webapp:advertisement_detail', pk=advertisement_pk)
        else:
            return HttpResponseForbidden("Вы не можете удалить этот комментарий")

webapp/templates/advertisement/advertisement_list_moderator.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        {% for ad in advertisements %}
            <div class="col-lg-4 col-md-6 mb-4">
                <a style="text-decoration: none" href="{% url 'webapp:advertisement_detail' ad.pk %}">
                    <div class="card" style="width: 300px; height: 560px">
                        <img style="width: 299px; height: 320px" src="{{ ad.photo.url }}" class="card-img-top"
                             alt="Photo">
                        <div class="card-body">
                            <span class="card-text"><b><a class="text-dark" style="text-decoration: none"
                                                          href="{% url 'accounts:user_detail' ad.author.pk %}">{{ ad.author }}</a></b>
                            </span><br>
                            <span>{{ ad.author.phone_number }}</span>
                            <p class="card-text"><b>Заголовок:</b> {{ ad.title }}</p>
                            <p class="card-text"><b>Статус:</b> <span id="status-{{ ad.pk }}">{{ ad.get_status_display }}</span></p>
                            <p class="card-text"><b>Цена:</b> {{ ad.price }} сом</p>
                            <div class="card_link">
                                <a class="btn btn-primary action-link"
                                   href="{% url 'webapp:approve_advertisement' pk=ad.pk %}"
                                   data-pk="{{ ad.pk }}">Одобрить</a>
                                <a class="btn btn-danger action-link"
                                   href="{% url 'webapp:reject_advertisement' pk=ad.pk %}"
                                   data-pk="{{ ad.pk }}">Отклонить</a>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

webapp/templates/advertisement/create_advertisement.html
{% extends 'base.html' %}
{% block title %}Создать объявление{% endblock %}

{% block content %}
    <h1 class="mt-5 mb-3">Создать объявление</h1>
    {% include 'partial/form.html' with form_method="post" is_data=True value_submit='Создать' fields_only=False action_url=request.path %}
{% endblock %}

webapp/templates/advertisement/detail.html
{% extends 'base.html' %}
{% block content %}
    <img style="border-radius: 10px" src="{{ advertisement.photo.url }}" alt="Photo">
    <h3 class="mt-3 mb-3">{{ advertisement.title }}</h3>
    <p><b>Описание:</b> {{ advertisement.description }}</p>
    <p><b>Статус:</b> {{ advertisement.get_status_display }}</p>
    <p><b>Категория:</b> {{ advertisement.category }}</p>
    <p><b>Цена:</b> {{ advertisement.price }} сом</p>
    <p><b>Автор:</b> <a class="text-dark" style="text-decoration: none"
                        href="{% url 'accounts:user_detail' advertisement.author.pk %}">{{ advertisement.author }}</a>
    </p>
    <p>{{ advertisement.created_at }}</p>
    {% if advertisement.author == request.user %}
        <div class="mb-3" style="display: flex">
            <a class="btn btn-primary me-3" href="{% url 'webapp:update_advertisement' advertisement.pk %}">Изменить</a>
            <form action="{% url 'webapp:mark_as_pending_deletion' advertisement.pk %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Удалить</button>
            </form>
        </div>
    {% endif %}
    {% if request.user.is_authenticated and not advertisement.author == request.user %}
        <form method="post" action="{% url 'webapp:comment_create' pk=advertisement.pk %}">
            {% csrf_token %}
            <input type="text" name="text" placeholder="Введите текст">
            <button class="btn btn-primary" type="submit">Добавить</button>
        </form>
    {% endif %}

    <h2 class="mt-3">Комментарии:</h2>
    <div class="list-group">
        {% for comment in comments %}
            <div class="list-group-item mb-2" style="display: flex; justify-content: space-between">
                <div>
                    <span>
                    Автор: <a class="text-dark" style="text-decoration: none"
                              href="{% url 'accounts:user_detail' advertisement.author.pk %}">{{ comment.author }}</a>
                    </span>
                    <p class="mb-0">{{ comment.text }}</p>
                    <p>{{ comment.created_at }}</p>
                </div>
                <div class="mt-4">
                    {% if request.user == comment.author %}
                        <form method="post" action="{% url 'webapp:comment_delete' pk=comment.pk %}">
                            {% csrf_token %}
                            <button class="btn btn-danger" type="submit">Удалить</button>
                        </form>
                    {% endif %}
                </div>
            </div>
        {% empty %}
            <div class="list-group-item">
                Нет комментариев.
            </div>
        {% endfor %}
    </div>
{% endblock %}

webapp/templates/advertisement/edit_advertisement.html
{% extends 'base.html' %}
{% block title %}Редактирование объявления{% endblock %}

{% block content %}
    <h1 class="mt-5 mb-3">Редактировать объявление</h1>
    {% include 'partial/form.html' with form_method="post" is_data=True value_submit='Сохранить' fields_only=False action_url=request.path %}
{% endblock %}

webapp/templates/advertisement/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        {% for ad in published_ads %}
            <div class="col-lg-4 col-md-6 mb-4">
                <a style="text-decoration: none" href="{% url 'webapp:advertisement_detail' ad.pk %}">
                    <div class="card" style="width: 300px; height: 530px">
                        <img style="width: 299px; height: 320px" src="{{ ad.photo.url }}" class="card-img-top"
                             alt="Photo">
                        <div class="card-body">
                            <span class="card-text"><b><a class="text-dark" style="text-decoration: none"
                                                       href="{% url 'accounts:user_detail' ad.author.pk %}">{{ ad.author }}</a></b>
                            </span><br>
                            <span>{{ ad.author.phone_number }}</span>
                            <p class="card-text"><b>Заголовок:</b> {{ ad.title }}</p>
                            <p class="card-text"><b>Описание:</b> {{ ad.description }}</p>
                            <p class="card-text"><b>Цена:</b> {{ ad.price }} сом</p>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}